version: 2

models:
  - name: fact_trips
    description: "Fact table for trip."
    columns:
      - name: trip_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: start_station_id
        description: "The foreign key to the station dimension table"
        tests:
          - relationships:
              # Uncomment the line 'arguments:' to resolve
              # MissingArgumentsPropertyInGenericTestDeprecation Warnings
              # Warnings appear dbt-core >= 1.10 environment
              # 'arguments:' will not work in older versions of dbt < 1.10
              arguments:
                to: ref('dim_station')
                field: station_id